### ISSUE TITLE
Unable to connect to RDS database with SSL required

### ISSUE THREAD

**Issue by jamesmbourne** [disneystreaming/pg2k4j#18]
There doesn't appear to be a parameter allowing the SSL mode to be specified when connecting to a database.

This causes the DB connection to fail if SSL is required.

pg2kinesis exposes this option as `--pg--sslmode` ([see here](https://github.com/handshake/pg2kinesis/blob/master/pg2kinesis/__main__.py#L17)).

**Comment by rkass** [comment]
After https://github.com/disneystreaming/pg2k4j/pull/19 is merged, this can be solved by adding `pgsslmode=require` to your pg2k4j invocation. Does this cover your use case? Feel free to give that pull request a review.

**Comment by jamesmbourne** [comment]
@rkass That should cover our use case perfectly. Thanks for getting this resolved so quickly!

**Comment by rkass** [comment]
Great, this should be addressed in the latest release https://github.com/disneystreaming/pg2k4j/releases/tag/1.0.2 . Closing this out. Please reach out if you have any trouble with these optioons
