### ISSUE TITLE
unknown flag: --awsaccesskey

### ISSUE THREAD

**Issue by fbridger** [disneystreaming/pg2k4j#22]
It would be great if we could run the docker container just by passing the Access Key and Secret. The code seems to be supporting this but Docker is throwing an error when specifying those parameters.

> docker run -v disneystreaming/pg2k4j --awsaccesskey=AccessKey--awssecret=Secret --region=us-east-2 --pgdatabase=AAAAA --pghost=BBBBB --pguser=CCCCC --pgpassword=DDDD --streamname=EEEEE

> unknown flag: --awsaccesskey
See 'docker run --help'.

**Comment by rkass** [comment]
@fbridger I'm unable to reproduce this. I just ran the following without error.
```
docker run disneystreaming/pg2k4j --awsaccesskey=AccessKey --awssecret=Secret --region=us-east-1 --pgdatabase=DB --pghost=HOST --pguser=USER --pgpassword=PW --streamname=STREAM
```
I do notice that in your command there's no space between the --awsaccesskey parameter and the --awssecret parameters. Could that be your issue?

**Comment by fbridger** [comment]
@rkass It's not that. Seems that when you use the **-v** parameter before the image it will generate this error.

If you try the following command you'll get the error:
```
docker run -v disneystreaming/pg2k4j --region=us-east-2 --pgdatabase=db --pghost=host.domain.us-east-2.rds.amazonaws.com --pguser=user --pgpassword=pass --streamname=stream --awsaccesskey=ACCESSKEY --awssecret=Key
```
> unknown flag: --region

Removing the **-v** parameter solves the issue

```
docker run disneystreaming/pg2k4j --region=us-east-2 --pgdatabase=db --pghost=host.domain.us-east-2.rds.amazonaws.com --pguser=user --pgpassword=pass --streamname=stream --awsaccesskey=ACCESSKEY --awssecret=Key
```
