### ISSUE TITLE
pg2k4j fails when `xid`s are between 32-bit int max and unsigned 32-bit int max

### ISSUE THREAD

**Issue by teej** [disneystreaming/pg2k4j#24]
Postgres transaction IDs are of type `xid`, unsigned 32-bit int. pg2k4j assumes they are _signed_ 32-bit ints https://github.com/disneystreaming/pg2k4j/blob/master/src/main/java/com/disneystreaming/pg2k4j/models/SlotMessage.java#L35. This causes JSON parsing of WAL messages into SlotMessage to fail with `com.fasterxml.jackson.core.JsonParseException: Numeric value (...) out of range of int` when a there's an xid between signed 32bit int max and unsigned 32bit int max.

**Comment by teej** [comment]
I don’t know enough Java to suggest a fix, but switching to long works for me locally.

**Comment by rkass** [comment]
Thanks for submitting @teej we'll get this looked at and fixed this week.

**Comment by rkass** [comment]
@teej you're right it does seem that postgres uses unsigned ints for the transaction id field, though I had a tough time finding that info in any postgres documentation. I found this which indicates that the transaction id is unsigned but this seems far from official: http://www.interdb.jp/pg/pgsql05.html . If you found any official documentation that says this please point me in that direction.

See this pr for a fix https://github.com/disneystreaming/pg2k4j/pull/26 . This pr just changes the xid field from an int to a long as you suggested

**Comment by teej** [comment]
The official Postrgres documentation calls them "32-bit quantities" 

> Another identifier type used by the system is xid, or transaction (abbreviated xact) identifier. This is the data type of the system columns xmin and xmax. Transaction identifiers are 32-bit quantities.

https://www.postgresql.org/docs/current/datatype-oid.html

The Postgres source defines `TransactionId` as type `uint32` https://github.com/postgres/postgres/blob/REL_11_0/src/include/c.h#L474

I wish their documentation was less ambiguous but that's what I've got for ya. Thanks for the fix!

**Comment by rkass** [comment]
This issue is fixed in the latest release https://github.com/disneystreaming/pg2k4j/releases/tag/1.0.6 . Please reopen if you see it again and great catch!
